name: 🚀 - New Bounty
description: Add a new bounty.
title: "🆕 Bounty - <BOUNTY NAME>"
labels: [Bounty]
assignees:
  - SirAh0
body:
  - type: dropdown
    id: is-core-select
    attributes:
      label: Roles Selection
      description: Multiple Selection. Which roles can claim this bounty.
      multiple: true
      options:
        - "Core"
        - "Contributor"
        - "Community"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Bounty Name
    validations:
      required: true

  - type: input
    id: dai
    attributes:
      label: DAI Payment
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe Bounty
    validations:
      required: true

