name: 🚀 - New Bounty
description: Add a new bounty.
title: "[🆕Bounty] <BOUNTY NAME>"
labels: [Bounty]
assignees:
  - SirAh0
body:
  - type: dropdown
    id: roles
    attributes:
      label: ◾Roles◾
      description: Multiple Selection. Which roles can claim this bounty.
      multiple: true
      options:
        - "Core"
        - "Contributor"
        - "Community"
    validations:
      required: true

  - type: dropdown
    id: verticle
    attributes:
      label: ◾SCRF Verticles◾
      description: Multiple Selection. Which SCRF Verticle(s) created this bounty.
      multiple: true
      options:
        - "Engagement"
        - "Content"
        - "Operations"
        - "Discovery"
        - "Outreach"
    validations:
      required: true      

  - type: dropdown
    id: levels
    attributes:
      label: Levels
      description: Multiple Selection, please see below table for reference.
      multiple: true
      options:
        - "4"
        - "3"
        - "2"
        - "1"
    validations:
      required: true              

  - type: markdown
    attributes:
      value: |
        |Levels	  |Time Frame (hours) |Effort  h per week  |Approval Type      |Bounty Tasks    |Bounty Amount per hour    |Importance          |
        |---------|-------------------|--------------------|-------------------|----------------|--------------------------|--------------------|
        |Level 4	|480                |20	                 |Regular Meetings	 | Unclear Goal   |                          |High - Must Get done|

        Level 3	240	20	Frequent Meetings and approval after completion of each task	Clear Goal, Open ended Tasks		High - Must Get done																		
        Level 2	80	10	Approval after completion 	Clearly Defined Multiline Task list 	25	Medium - Needs to done, needs to be chased																		
        Level 1	40	5	No Approval required	Single Tasks	15	Low - Ok if not done , no need of chasing																		        

  - type: input
    id: name
    attributes:
      label: Bounty Name
    validations:
      required: true

  - type: input
    id: dai
    attributes:
      label: DAI Payment
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe Bounty
    validations:
      required: true
