name: 🚀 - New Bounty
description: Add a new bounty.
title: "🆕 Bounty - "
labels: [Bounty]
assignees:
  - SirAh0
body:
  - type: dropdown
    id: is-core-select
    attributes:
      label: Roles Selection
      description: Multiple Selection. Which roles can claim this bounty.
      multiple: true
      options:
        - "Core"
        - "Contributor"
        - "Community"

